namespace Basics.Arrays.Examples;

public class Exercise007 {
    // Pascal’s triangle. As we know from mathematics, the first row of the triangle contains the number 1 and
    // each next number is generated by sum of the two numbers on the row above it.

    public static void UserMain() { }
}